using System.Text.Json;
using AgentClient.Infrastructure.Observability;
using Microsoft.Agents.AI;

namespace AgentClient.Workflow;

public static class TypedAgentRunner
{
    public static async ValueTask<string> RunActionAsync(
        AIAgent agent,
        object input,
        WorkflowRunMetadata metadata,
        string agentName,
        string step,
        int iteration,
        string instruction,
        int timeoutSeconds = 90)
    {
        using var context = WorkflowRunContext.BeginStep(metadata, agentName, step, iteration);
        using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(timeoutSeconds));
        var json = JsonSerializer.Serialize(input, JsonSerializerOptions.Web);
        var response = await agent.RunAsync(
            $"{instruction}\nВходной контракт:\n{json}",
            cancellationToken: timeout.Token);

        return response.ToString();
    }

    public static async ValueTask<T> RunAsync<T>(
        AIAgent agent,
        object input,
        WorkflowRunMetadata metadata,
        string agentName,
        string step,
        int iteration)
    {
        using var context = WorkflowRunContext.BeginStep(metadata, agentName, step, iteration);
        var json = JsonSerializer.Serialize(input, JsonSerializerOptions.Web);
        var prompt = $"Входной typed-контракт в JSON:\n{json}\n\nВерни заполненный результат своего контракта.";
        if (!string.Equals(
                Environment.GetEnvironmentVariable("MODEL_PROVIDER"),
                "gemini",
                StringComparison.OrdinalIgnoreCase))
        {
            var response = await agent.RunAsync<T>(prompt, serializerOptions: JsonSerializerOptions.Web);
            return response.Result;
        }

        // Gemini's OpenAI-compatible endpoint supports tools, but can reject the
        // JSON Schema generated by Agent Framework's generic RunAsync<T>. Keep
        // the typed contract and governance checks, while asking for JSON in the
        // prompt and deserializing it locally.
        var untypedResponse = await agent.RunAsync(prompt);
        var content = untypedResponse.ToString().Trim();
        if (content.StartsWith("```", StringComparison.Ordinal))
        {
            var firstNewLine = content.IndexOf('\n');
            var closingFence = content.LastIndexOf("```", StringComparison.Ordinal);
            if (firstNewLine >= 0 && closingFence > firstNewLine)
            {
                content = content[(firstNewLine + 1)..closingFence].Trim();
            }
        }

        return JsonSerializer.Deserialize<T>(content, JsonSerializerOptions.Web)
            ?? throw new JsonException($"Gemini вернул пустой typed-контракт для {typeof(T).Name}.");
    }
}
